language: python
python:
  - 3.4
  - 3.5
  - pypy3
install:
 - pip install -r requirements.txt
 - pip install -r test-requirements.txt
script:
 - nosetests -v -l DEBUG --logging-level=DEBUG --with-coverage --cover-package=flask_webapi